"""add fav/ret columns

Revision ID: 36b2fa93dd2f
Revises: 
Create Date: 2020-07-19 14:13:27.425174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b2fa93dd2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('favorite_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('favorited', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('retweet_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('retweeted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'retweeted')
    op.drop_column('messages', 'retweet_count')
    op.drop_column('messages', 'favorited')
    op.drop_column('messages', 'favorite_count')
    # ### end Alembic commands ###
